#!/bin/ash

echo "Start CSpot (Spotify Connect)"

APPNAME=cspotcli

# check connection first
until ping apresolve.spotify.com -c 1 | grep ttl
do
    sleep .5
    echo "Wait established connection"
done

cspotcli -d "plughw:0,0" -n rpi0w_dev > /dev/null 2&>1 &

if [ $? -ne 0 ]; then
    echo "Cannot start $APPNAME"
else
    echo "$APPNAME start successfully"
fi

